project_id = "nikvolkksngggjkvpzrd"

[functions.create-checkout]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.submit-challenge-score]
verify_jwt = false

[functions.complete-drill]
verify_jwt = false

[functions.get-drills]
verify_jwt = false

[functions.get-drill]
verify_jwt = false

[functions.get-categories]
verify_jwt = false

[functions.get-user-completed-drills]
verify_jwt = false
